In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('df_Richmond Point Potrero_USA_Clima.csv')

In [3]:
df_summer = df[(df.month >= 6) & (df.month <= 8)]
df_summer

,Unnamed: 0,year,month,day,hour,DBT,DPT,RH,p_atm,extr_hor_rad,...,utci_noSun_Wind_categories,utci_noSun_noWind_categories,utci_Sun_Wind_categories,utci_Sun_noWind_categories,p_sat,p_vap,hr,t_wb,t_dp,h
3624,2019-06-01 09:00:00+00:00,2016,6,1,1,12.9,9.9,82,101122,0,...,-1,0,-1,0,1488.0,1220.160,0.007581,10.9,9.9,32088.71
3625,2019-06-01 10:00:00+00:00,2016,6,1,2,12.9,9.9,82,101087,0,...,-1,0,-1,0,1488.0,1220.160,0.007581,10.9,9.9,32088.71
3626,2019-06-01 11:00:00+00:00,2016,6,1,3,12.8,9.8,82,101059,0,...,-1,0,-1,0,1478.3,1212.206,0.007531,10.8,9.8,31860.69
3627,2019-06-01 12:00:00+00:00,2016,6,1,4,12.7,9.7,82,101057,0,...,-1,0,-1,0,1468.7,1204.334,0.007482,10.7,9.7,31634.01
3628,2019-06-01 13:00:00+00:00,2016,6,1,5,12.7,9.7,82,101067,0,...,-1,0,-1,0,1468.7,1204.334,0.007482,10.7,9.7,31634.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5827,2019-09-01 04:00:00+00:00,2017,8,31,20,26.2,23.2,84,100720,0,...,1,1,1,1,3403.1,2858.604,0.018057,24.0,23.1,72318.95
5828,2019-09-01 05:00:00+00:00,2017,8,31,21,26.5,23.5,84,100750,0,...,1,1,1,1,3463.9,2909.676,0.018389,24.3,23.4,73476.50
5829,2019-09-01 06:00:00+00:00,2017,8,31,22,24.1,21.1,83,100892,0,...,0,1,0,1,3003.1,2492.573,0.015686,21.9,20.9,64110.60
5830,2019-09-01 07:00:00+00:00,2017,8,31,23,21.4,18.4,83,101020,0,...,0,0,0,0,2549.5,2116.085,0.013267,19.3,18.3,55177.75
5831,2019-09-01 08:00:00+00:00,2017,8,31,24,18.4,15.4,83,101144,0,...,0,0,0,0,2116.8,1756.944,0.010975,16.4,15.4,46287.20

In [4]:
df_winter = df[(df.month >= 12) | (df.month <= 2)]
df_winter

,Unnamed: 0,year,month,day,hour,DBT,DPT,RH,p_atm,extr_hor_rad,...,utci_noSun_Wind_categories,utci_noSun_noWind_categories,utci_Sun_Wind_categories,utci_Sun_noWind_categories,p_sat,p_vap,hr,t_wb,t_dp,h
0,2019-01-01 09:00:00+00:00,2012,1,1,1,13.2,10.2,82,102038,0,...,0,0,0,0,1517.5,1244.350,0.007733,11.2,10.2,32778.22
1,2019-01-01 10:00:00+00:00,2012,1,1,2,11.6,8.6,82,102038,0,...,-1,0,-1,0,1366.0,1120.120,0.006953,9.7,8.6,29180.62
2,2019-01-01 11:00:00+00:00,2012,1,1,3,11.9,8.9,82,102028,0,...,-1,0,-1,0,1393.4,1142.588,0.007094,10.0,8.9,29841.39
3,2019-01-01 12:00:00+00:00,2012,1,1,4,11.5,8.5,82,102057,0,...,-2,0,-2,0,1357.0,1112.740,0.006906,9.6,8.5,28962.17
4,2019-01-01 13:00:00+00:00,2012,1,1,5,11.8,8.8,82,102048,0,...,-1,0,-1,0,1384.2,1135.044,0.007046,9.9,8.8,29620.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2020-01-01 04:00:00+00:00,2015,12,31,20,9.5,6.5,82,102047,0,...,-1,0,-1,0,1187.5,973.750,0.006035,7.6,6.6,24735.85
8756,2020-01-01 05:00:00+00:00,2015,12,31,21,8.0,5.0,81,102056,0,...,-1,0,-1,0,1072.8,868.968,0.005380,6.1,4.9,21565.75
8757,2020-01-01 06:00:00+00:00,2015,12,31,22,7.7,4.7,81,102026,0,...,-1,0,-1,0,1051.1,851.391,0.005271,5.8,4.6,20985.62
8758,2020-01-01 07:00:00+00:00,2015,12,31,23,6.8,3.8,81,102035,0,...,-1,-1,-1,-1,988.3,800.523,0.004953,4.9,3.8,19275.74
8759,2020-01-01 08:00:00+00:00,2015,12,31,24,6.4,3.4,81,101985,0,...,-1,-1,-1,-1,961.4,778.734,0.004817,4.6,3.4,18529.20

# Average parameters

In [5]:
c = ['DBT', 'RH', 'dif_hor_rad', 'wind_speed', 'tot_sky_cover', 'Pwater']
for i in c:
    print(i)
    print(df_summer[i].mean())

DBT
15.73301630434783
RH
77.92436594202898
dif_hor_rad
89.92572463768116
wind_speed
4.546331521739244
tot_sky_cover
2.5104166666666665
Pwater
32.5348731884058

In [6]:
for i in c:
    print(i)
    print(df_winter[i].mean())

DBT
11.57606481481483
RH
77.3787037037037
dif_hor_rad
36.69861111111111
wind_speed
3.3342592592592952
tot_sky_cover
3.7314814814814814
Pwater
22.022685185185185

# Daily temp range

In [15]:
df_max = df_summer.groupby(['month', 'day']).max()
df_min = df_summer.groupby(['month', 'day']).min()
df_range = df_max['DBT'] - df_min['DBT']
df_range.mean()

4.735869565217391

In [16]:
df_max = df_winter.groupby(['month', 'day']).max()
df_min = df_winter.groupby(['month', 'day']).min()
df_range = df_max['DBT'] - df_min['DBT']
df_range.mean()

6.0666666666666655